In [115]:
!pip3 install --upgrade pip
!pip3 install pandas 
!pip3 install numpy
!pip3 install sklearn
!pip3 install matplotlib

Defaulting to user installation because normal site-packages is not writeable
Defaulting to user installation because normal site-packages is not writeable
Defaulting to user installation because normal site-packages is not writeable
Defaulting to user installation because normal site-packages is not writeable
Defaulting to user installation because normal site-packages is not writeable


In [116]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

iris = pd.read_csv("./iris.csv", header=None)
dataset = np.array(iris)


       0    1    2    3  4
0    5.1  3.5  1.4  0.2  1
1    4.9  3.0  1.4  0.2  1
2    4.7  3.2  1.3  0.2  1
3    4.6  3.1  1.5  0.2  1
4    5.0  3.6  1.4  0.2  1
..   ...  ...  ...  ... ..
145  6.7  3.0  5.2  2.3  3
146  6.3  2.5  5.0  1.9  3
147  6.5  3.0  5.2  2.0  3
148  6.2  3.4  5.4  2.3  3
149  5.9  3.0  5.1  1.8  3

[150 rows x 5 columns]
[[5.1 3.5 1.4 0.2 1. ]
 [4.9 3.  1.4 0.2 1. ]
 [4.7 3.2 1.3 0.2 1. ]
 [4.6 3.1 1.5 0.2 1. ]
 [5.  3.6 1.4 0.2 1. ]
 [5.4 3.9 1.7 0.4 1. ]
 [4.6 3.4 1.4 0.3 1. ]
 [5.  3.4 1.5 0.2 1. ]
 [4.4 2.9 1.4 0.2 1. ]
 [4.9 3.1 1.5 0.1 1. ]
 [5.4 3.7 1.5 0.2 1. ]
 [4.8 3.4 1.6 0.2 1. ]
 [4.8 3.  1.4 0.1 1. ]
 [4.3 3.  1.1 0.1 1. ]
 [5.8 4.  1.2 0.2 1. ]
 [5.7 4.4 1.5 0.4 1. ]
 [5.4 3.9 1.3 0.4 1. ]
 [5.1 3.5 1.4 0.3 1. ]
 [5.7 3.8 1.7 0.3 1. ]
 [5.1 3.8 1.5 0.3 1. ]
 [5.4 3.4 1.7 0.2 1. ]
 [5.1 3.7 1.5 0.4 1. ]
 [4.6 3.6 1.  0.2 1. ]
 [5.1 3.3 1.7 0.5 1. ]
 [4.8 3.4 1.9 0.2 1. ]
 [5.  3.  1.6 0.2 1. ]
 [5.  3.4 1.6 0.4 1. ]
 [5.2 3.5 1.5 0.2 1. ]
 [5.2 3.

In [117]:
# split data, target
data = dataset[:, 0:4]
target = dataset[:, 4]


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [118]:
# HW01 : Accuracy

# train & test of KNeighborclassifier 
from sklearn.neighbors import KNeighborsClassifier

# tarin_test_split
train_input, test_input, train_target, test_target = train_test_split(data, target, random_state=0)

In [119]:
# k = 1
kn_1 = KNeighborsClassifier()
kn_1.n_neighbors = 1

# train
kn_1.fit(train_input, train_target)

# accuracy of k = 1
print("k=1일 때 테스트 셑의 정확도: {:.2f}".format(kn_1.score(test_input, test_target)))

k=1일 때 테스트 셑의 정확도: 0.97


In [120]:
# k = 5
kn_5 = KNeighborsClassifier()
kn_5.n_neighbors = 5

# train
kn_5.fit(train_input, train_target)

# accuracy of k = 5
print("k=5일 때 테스트 셑의 정확도: {:.2f}".format(kn_5.score(test_input, test_target)))

k=5일 때 테스트 셑의 정확도: 0.97


In [121]:
# k = 10
kn_10 = KNeighborsClassifier()
kn_10.n_neighbors = 10

# train
kn_10.fit(train_input, train_target)

# accuracy of k = 10
print("k=10일 때 테스트 셑의 정확도: {:.2f}".format(kn_10.score(test_input, test_target)))

k=10일 때 테스트 셑의 정확도: 0.97


In [122]:
# HW02 : Normalization
from matplotlib import pyplot as plt

iris_mod = pd.read_csv("./iris_mod.csv", header=None)
dataset_mod = np.array(iris_mod)

data_mod = dataset_mod[:, 0:4]
target_mod = dataset_mod[:, 4]

In [123]:
# get : min, MAX
data_min = data_mod.min(axis = 0)
data_max = data_mod.max(axis = 0)

# normalization
data_norm = (data_mod - data_min) / (data_max - data_min)

In [124]:
# tarin_test_split
mod_train_input, mod_test_input, mod_train_target, mod_test_target = train_test_split(data_mod, target_mod, random_state=0)
norm_train_input, norm_test_input, norm_train_target, norm_test_target = train_test_split(data_norm, target_mod, random_state=0)


# before normaliation
mod_kn = KNeighborsClassifier()
mod_kn.n_neighbors = 1
mod_kn.fit(mod_train_input, mod_train_target)

# after normalization
norm_kn = KNeighborsClassifier()
norm_kn.n_neighbors = 1
norm_kn.fit(norm_train_input, norm_train_target)

# accuracy of k = 1
print("k=1일 때 normalization 수행 전 테스트 셑의 정확도: {:.2f}".format(mod_kn.score(mod_test_input, mod_test_target)))
print("k=1일 때 normalization 수행 후 테스트 셑의 정확도: {:.2f}".format(norm_kn.score(norm_test_input, norm_test_target)))

k=1일 때 normalization 수행 전 테스트 셑의 정확도: 0.66
k=1일 때 normalization 수행 후 테스트 셑의 정확도: 0.97
